### ISSUE TITLE
Hearthkyn Grudge Tokens

### ISSUE THREAD

**Issue by GeorgePratt** [jmegner/KT21Calculator#5]
At the moment your calculator cannot correctly simulate these as these turn hits into crits, but you must roll those hits. Autocrit just retains a crit without rolling. Since you can stack grudge tokens and turn multiple hits into crits, autoretaining more than 1 crit skews the data to be stronger than it actually is.

**Comment by jmegner** [comment]
I guess I could implement general "PromoteFailsToHits" and "PromoteHitsToCrits" numerical options for both shooting and melee.  This might happen in a month or two.

**Comment by jmegner** [comment]
https://github.com/jmegner/KT21Calculator/commit/e185b8fea93e691bcb48a02084c7b49588262c5c fixes this.
