### ISSUE TITLE
Cult Ambush / Rerolling specific values + Close Assault

### ISSUE THREAD

**Issue by Oust573** [jmegner/KT21Calculator#6]
Hi was wondering how difficult it would be to add an option for re-rolls of any results of a specific value (basically ceaseless+) - quite a few teams have this ability:
- Wyrmblade: Cult Ambush
- Breachers: Attack Order
- Warp Coven: Slow and Purposeful

and probably a few more that I can't think of. 

With Breachers being strong in the meta an option for Close Assault could be quite nice too (two successful hits upgrades a failed hit into a success) as it differs slightly from starfire/dakkadakkadakka

Such a great tool, have gotten so much use out of it and thank you for sharing!

**Comment by jmegner** [comment]
Implemented and I am belatedly updating this issue, whoops.
