### ISSUE TITLE
Additional Melee Abilities (Stealth Assault / Duellist)

### ISSUE THREAD

**Issue by Oust573** [jmegner/KT21Calculator#7]
Would abilities that allow the charging operative to strike twice in a row be possible to implement in the melee calculator? 
Void-dancers - Murderous Entrance (Can immediately resolve another attack dice following the resolution of a successful crit)
Phobos - Stealth Assault (Can immediately resolve another attack dice following the resolution of a successful hit)

Duellist (Parry before the combat begins) is also a common ability that appears on quite a few melee specialists and can significantly change how fights go - would that also be possible to implement?
Elucidian Starstriders - Assassin
Wyrmblade - Locus
Voidscarred - Kurnathi

There are also the damage reduction abilities that trigger off specific hits: 
Kommandos - Just a Scratch
Elucidian Starstriders - Undaunted Explorers (halve the damage of one attack die to a minimum of 2)
Warp Coven - Arcane Robes (one crit attack is reduced to normal damage)

JAS is probably the most important one currently

**Comment by jmegner** [comment]
Done: murderous entrance, pre-parry, just a scratch.

Hmm, arcane robes seems like the new/nerfed Intercession Durable, right?

**Comment by jmegner** [comment]
I'm gonna close this as completed and open a new one for Arcane Robes / nerfed Durable.
