### ISSUE TITLE
support multiple attacks from different weapons 

### ISSUE THREAD

**Issue by Pizzanui** [jmegner/KT21Calculator#8]
It would be helpful to be able to calculate the average damage and kill% against a single operative getting shot by two different weapon profiles. For example, a Warpcoven Sorcerer (under the benefit of Exalted Astartes) fires their Warpflame Pistol _and_ Doombolt, both at the same target. What is the likelihood of that target dying from the combination of those two shots?

**Comment by jmegner** [comment]
It just occurred to me I don't need a different tab for this.  With the accordions not taking up much vertical space, I can just put a combo results section under the individual situation results sections.
